// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfae9Pd7cE70fCjuOWSAH3A5fzTOtDiik',
    appId: '1:38977014405:android:97882089a26f2cb8ff37ec',
    messagingSenderId: '38977014405',
    projectId: 'edtech-f2d77',
    storageBucket: 'edtech-f2d77.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMTaCWBYJnSoByZPD0G4FU908kuQfIXR8',
    appId: '1:38977014405:web:125b1000d8242e1bff37ec',
    messagingSenderId: '38977014405',
    projectId: 'edtech-f2d77',
    authDomain: 'edtech-f2d77.firebaseapp.com',
    storageBucket: 'edtech-f2d77.appspot.com',
    measurementId: 'G-DMBG1KM6RT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE2CF1q8J6ii7AuIroldopeswqlQzk3X4',
    appId: '1:38977014405:ios:9ad02e27a620a568ff37ec',
    messagingSenderId: '38977014405',
    projectId: 'edtech-f2d77',
    storageBucket: 'edtech-f2d77.appspot.com',
    androidClientId: '38977014405-67j5rjhcvmcnuhnjtkjetjl3sh52bbev.apps.googleusercontent.com',
    iosClientId: '38977014405-ecanbiibmstfhgs2bevb3ic9afo49kt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.edtech',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE2CF1q8J6ii7AuIroldopeswqlQzk3X4',
    appId: '1:38977014405:ios:9ad02e27a620a568ff37ec',
    messagingSenderId: '38977014405',
    projectId: 'edtech-f2d77',
    storageBucket: 'edtech-f2d77.appspot.com',
    androidClientId: '38977014405-67j5rjhcvmcnuhnjtkjetjl3sh52bbev.apps.googleusercontent.com',
    iosClientId: '38977014405-ecanbiibmstfhgs2bevb3ic9afo49kt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.edtech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMTaCWBYJnSoByZPD0G4FU908kuQfIXR8',
    appId: '1:38977014405:web:f91e6a721171b748ff37ec',
    messagingSenderId: '38977014405',
    projectId: 'edtech-f2d77',
    authDomain: 'edtech-f2d77.firebaseapp.com',
    storageBucket: 'edtech-f2d77.appspot.com',
    measurementId: 'G-QC2S23WZ12',
  );

}